### ISSUE TITLE
[주간 목표] 최효종 march_week3 

### ISSUE THREAD

**Issue by bluedog129** [lawnmowing-programmer/algo#169]
## 📅 Period
2023-03-12 ~ 2023-03-18

## 📝  Todo
- [x] 본과정 push_swap
- [x] 영어 문법 English_Grammer_in_use 
- [x] #170
- [x] 알고리즘 한 문제 풀기 (boj 15649)

**Comment by minjae9610** [comment]
![image](https://user-images.githubusercontent.com/33440010/224975632-10932f2d-0116-46b5-86bb-150aa50c4081.png)
info 채워주세요!

**Comment by bluedog129** [comment]
> ![image](https://user-images.githubusercontent.com/33440010/224975632-10932f2d-0116-46b5-86bb-150aa50c4081.png) info 채워주세요!

info가... 뭐였을까요?

**Comment by minjae9610** [comment]
![image](https://user-images.githubusercontent.com/33440010/225216595-ef02bdb1-0a17-4f8c-a4e7-3e00c87a0f2a.png)
기간도 지정 부탁드릴께요!
