### ISSUE TITLE
[주간 목표] 임현순 week1 목표

### ISSUE THREAD

**Issue by Hyun-Soon** [lawnmowing-programmer/algo#43]
## 📅 Period
2023-02-27 ~ 2023-03-05

## 📝  Todo
- [ ] 알고리즘 강의 3-H(13913) 풀기
- [ ] 알고리즘 강의 3-I(17071) 풀기
- [ ] 알고리즘 강의 3-J(14497) 풀기
- [ ] 알고리즘 강의 3-K(3197) 풀기

**Comment by minjae9610** [comment]
오 알고리즘 강의라니 궁금해져서 그러는데 혹시 어떤 강의인지 질문드려도 괜찮으실까요?

**Comment by Hyun-Soon** [comment]
https://www.inflearn.com/course/10%EC%A3%BC%EC%99%84%EC%84%B1-%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8-%ED%81%B0%EB%8F%8C/dashboard
위 강의입니다! 
Todo list 괄호 안에 있는 숫자는 백준 문제번호에요

**Comment by minjae9610** [comment]
@Hyun-Soon 완료한 이슈는 Close로 바꿔주세요!
